//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        public long ConsultSID { get; set; }
        public string ConsultIEN { get; set; }
        public short Sta3n { get; set; }
        public Nullable<int> PatientSID { get; set; }
        public Nullable<int> PatientLocationSID { get; set; }
        public Nullable<int> ProtocolSID { get; set; }
        public Nullable<int> GMRCProcedureSID { get; set; }
        public string GMRCProcedure { get; set; }
        public Nullable<int> ClinicalProcedureSID { get; set; }
        public Nullable<int> ToRequestServiceSID { get; set; }
        public string ToRequestServiceName { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
        public string RequestVistaErrorDate { get; set; }
        public Nullable<long> RequestDateTimeTransformSID { get; set; }
        public int RequestDateSID { get; set; }
        public Nullable<System.DateTime> FileEntryDateTime { get; set; }
        public string FileEntryVistaErrorDate { get; set; }
        public Nullable<long> FileEntryDateTimeTransformSID { get; set; }
        public Nullable<int> FromLocationSID { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> ToStaffSID { get; set; }
        public Nullable<int> OrderStatusSID { get; set; }
        public Nullable<long> CPRSOrderSID { get; set; }
        public string CPRSStatus { get; set; }
        public Nullable<int> RecentActivityTypeSID { get; set; }
        public string RecentActivityType { get; set; }
        public Nullable<int> SendingStaffSID { get; set; }
        public string SignificantFindings { get; set; }
        public Nullable<int> UrgencyProtocolSID { get; set; }
        public string Urgency { get; set; }
        public Nullable<int> ConsultPlaceProtocolSID { get; set; }
        public string PlaceOfConsultation { get; set; }
        public string DisplayTextOfItemOrdered { get; set; }
        public Nullable<int> OrderingInstitutionSID { get; set; }
        public Nullable<short> OrderingSta3n { get; set; }
        public string InpatOutpat { get; set; }
        public string ProvisionalDiagnosis { get; set; }
        public string ProvisionalDiagnosisCode { get; set; }
        public string RemoteRole { get; set; }
        public string RemoteService { get; set; }
        public Nullable<int> RemoteConsultInstitutionSID { get; set; }
        public string RemoteConsultSta3n { get; set; }
        public Nullable<long> RemoteConsultSID { get; set; }
        public Nullable<long> TIUDocumentSID { get; set; }
        public Nullable<System.DateTime> EarliestDate { get; set; }
        public string EarliestVistaErrorDate { get; set; }
        public Nullable<long> EarliestDateTransformSID { get; set; }
    
        public virtual Telederm_Consult Telederm_Consult { get; set; }
    }
}
