//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_PathologyReport
    {
        public int ConditionPathologySID { get; set; }
        public int ConditionSID { get; set; }
        public string FinalDiagnosis { get; set; }
        public Nullable<int> ICD9SID { get; set; }
        public Nullable<int> ICD10SID { get; set; }
        public Nullable<int> CPC_CorrelationSID { get; set; }
        public Nullable<decimal> BreslowThickness { get; set; }
        public string MitoticIndex { get; set; }
        public Nullable<int> TNM_StageSID { get; set; }
        public Nullable<int> PathologistSID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    
        public virtual Telederm_Condition Telederm_Condition { get; set; }
    }
}
