//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_Condition
    {
        public Telederm_Condition()
        {
            this.Telederm_TreatmentRequest = new HashSet<Telederm_TreatmentRequest>();
            this.Telederm_PathologyReport = new HashSet<Telederm_PathologyReport>();
        }
    
        public int ConditionSID { get; set; }
        public int PatientSID { get; set; }
        public Nullable<int> ICD9SID { get; set; }
        public Nullable<int> ICD10SID { get; set; }
        public Nullable<short> LocationSID { get; set; }
        public string LocationText { get; set; }
        public Nullable<System.DateTime> FoundDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<bool> SuspectedMelanoma { get; set; }
    
        public virtual Telederm_Patient Telederm_Patient { get; set; }
        public virtual ICollection<Telederm_TreatmentRequest> Telederm_TreatmentRequest { get; set; }
        public virtual ICollection<Telederm_PathologyReport> Telederm_PathologyReport { get; set; }
    }
}
