//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_TreatmentRequest
    {
        public int TreatmentRequestSID { get; set; }
        public int ConditionSID { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<int> ProviderSID { get; set; }
        public Nullable<int> ProcedureSID { get; set; }
    
        public virtual Telederm_Condition Telederm_Condition { get; set; }
    }
}
