//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_PathologyReportRaw
    {
        public int PathologyReportRawSID { get; set; }
        public int PatientSID { get; set; }
        public string PathologyReportRaw { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
    
        public virtual Telederm_Patient Telederm_Patient { get; set; }
    }
}
