//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_DifferentialDiagnosis
    {
        public int DiffDxSID { get; set; }
        public int ConditionSID { get; set; }
        public long ConsultSID { get; set; }
        public Nullable<int> ICD9SID { get; set; }
        public Nullable<int> ICD10SID { get; set; }
        public Nullable<int> DiffDxOrdinal { get; set; }
    }
}
