//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_Patient
    {
        public Telederm_Patient()
        {
            this.Telederm_PatientAddress = new HashSet<Telederm_PatientAddress>();
            this.Telederm_PathologyReportRaw = new HashSet<Telederm_PathologyReportRaw>();
            this.Telederm_Consult = new HashSet<Telederm_Consult>();
            this.Telederm_Condition = new HashSet<Telederm_Condition>();
        }
    
        public int PatientSID { get; set; }
        public string PatientICN { get; set; }
        public Nullable<bool> IsSCSC { get; set; }
    
        public virtual ICollection<Telederm_PatientAddress> Telederm_PatientAddress { get; set; }
        public virtual ICollection<Telederm_PathologyReportRaw> Telederm_PathologyReportRaw { get; set; }
        public virtual ICollection<Telederm_Consult> Telederm_Consult { get; set; }
        public virtual ICollection<Telederm_Condition> Telederm_Condition { get; set; }
        public virtual SPatient SPatient { get; set; }
    }
}
