//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telederm_Consult
    {
        public long ConsultSID { get; set; }
        public int PatientSID { get; set; }
        public Nullable<int> RequestingProviderSID { get; set; }
        public Nullable<int> ReadingProviderSID { get; set; }
        public Nullable<int> ImagerSID { get; set; }
        public Nullable<int> OrderingInstitutionSID { get; set; }
        public Nullable<int> RequestServiceSID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<long> RemoteConsultSID { get; set; }
        public string ImageComments { get; set; }
    
        public virtual Telederm_Patient Telederm_Patient { get; set; }
        public virtual Consult Consult { get; set; }
    }
}
